BACKBONE: "resnet101"
HEAD_DIM: 1024
PROPOSAL_METHOD: "CONNECTED_COMPONENTS"
WARPED_SIZE: 250
CLASSES: ["Section Header", "Body Text", "Figure", "Figure Caption", "Table", "Equation",
      "Page Footer", "Page Header", "Table Caption",  "Other", "Reference text"]
TRAINING: False
